---
## Author
author:
  name: Бабаев Рахим
  degrees: DSc
  orcid: 0000-0002-0877-7063
  email: kulyabov-ds@rudn.ru
  affiliation:
    - name: Российский университет дружбы народов
      country: Российская Федерация
      postal-code: 117198
      city: Москва
      address: ул. Миклухо-Маклая, д. 6

## Title
title: "Отчёт по лабораторной работе №1"
subtitle: "Бабаев Рахим"
license: "CC BY"
---

# Цель работы

Целью лабораторной работы является изучение методов кодирования и модуляции сигналов в среде Octave, а также получение практических навыков построения графиков, спектрального анализа и исследования свойств различных кодов передачи данных.

# Задание

В ходе работы требовалось выполнить задания, приведённые в методических указаниях: построить графики заданных тригонометрических функций в Octave, реализовать разложение импульсного сигнала в частичный ряд Фурье, определить спектры отдельных сигналов и их суммы, продемонстрировать амплитудную модуляцию и исследовать кодирование сигнала с проверкой свойства самосинхронизации. В отчёте необходимо описать порядок выполнения работы и сформулировать выводы по полученным результатам. 

# Теоретическое введение

Сигналом называют физическую величину, несущую информацию и изменяющуюся во времени. Для анализа сигналов используют разложение в ряд Фурье и быстрое преобразование Фурье, позволяющие определить частотный состав сигнала и его спектральные характеристики. 

Модуляция применяется для переноса информационного сигнала на высокочастотную несущую. В данной работе рассматривалась амплитудная модуляция, при которой амплитуда несущего сигнала изменяется по закону модулирующего сигнала.

Кодирование сигнала на физическом уровне определяет способ представления битовой последовательности электрическими импульсами. В работе исследовались униполярное кодирование, AMI, NRZ, RZ, манчестерское и дифференциальное манчестерское кодирование, а также их спектры и свойства самосинхронизации. 

# Выполнение лабораторной работы

1. В начале работы была подготовлена среда Octave для выполнения всех расчётов и построения графиков. После запуска редактора сценариев были созданы отдельные `.m`-файлы под каждое задание, чтобы результаты можно было запускать и проверять независимо друг от друга.

2. Для первого задания был создан сценарий построения графика функции $y_1 = \sin x + rac{1}{3}\sin 3x + rac{1}{5}\sin 5x$ на интервале от -10 до 10. В сценарии был сформирован массив значений `x`, вычислен массив `y1`, после чего график построен функцией `plot`, подписаны оси и выполнен экспорт результата в файлы форматов `.eps` и `.png`.

3. Далее был изменён сценарий так, чтобы на одном графике одновременно отображались две функции: $y_1 = \sin x + rac{1}{3}\sin 3x + rac{1}{5}\sin 5x$ и $y_2 = \cos x + rac{1}{3}\cos 3x + rac{1}{5}\cos 5x$. Это позволило сравнить форму обеих кривых и убедиться, что Octave корректно поддерживает одновременное построение нескольких графиков в одной системе координат. 

4. На следующем этапе был реализован сценарий разложения меандра в частичный ряд Фурье. Для этого были заданы количество гармоник, массив времени, амплитуда и период сигнала, после чего вычислены нечётные гармоники и коэффициенты ряда, поскольку именно нечётные гармоники формируют меандр.

5. После вычисления коэффициентов был сформирован массив гармоник и массив элементов ряда, а затем выполнено накопительное суммирование с помощью `cumsum`. Построение графиков через `subplot` показало, как с увеличением числа гармоник форма сигнала всё больше приближается к меандру.

6. Затем был подготовлен сценарий для определения спектра двух синусоидальных сигналов с частотами 10 Гц и 40 Гц и амплитудами 1 и 0.7 соответственно. После задания параметров дискретизации были построены графики самих сигналов, а затем через функцию `fft` вычислены их спектры.

7. Для корректного отображения спектров были отброшены дублирующие отрицательные частоты и выполнена нормировка амплитуд. В результате на графике были отчётливо видны спектральные пики, соответствующие частотам исходных синусоидальных сигналов.

8. После этого был исследован спектр суммы двух сигналов. Сначала был построен суммарный сигнал как результат сложения двух синусоид, а затем по нему вычислен спектр, который показал наличие тех же частотных составляющих, что и у отдельных сигналов.

9. В отдельном каталоге был выполнен сценарий амплитудной модуляции. Для этого были заданы низкочастотный сигнал с частотой 5 Гц и несущая с частотой 50 Гц, после чего получен модулированный сигнал как произведение двух синусоид и построена его огибающая.

10. Далее был вычислен спектр амплитудно-модулированного сигнала. Полученный график показал, что спектр произведения сигналов соответствует свёртке спектров и содержит характерные боковые составляющие относительно несущей частоты.

11. На заключительном этапе была выполнена работа по кодированию битовых последовательностей. Для этого были созданы файлы `main.m`, `maptowave.m`, `unipolar.m`, `ami.m`, `bipolarnrz.m`, `bipolarrz.m`, `manchester.m`, `diffmanc.m` и `calcspectre.m`, в которых реализованы соответствующие способы преобразования входной последовательности в сигнал.

12. После подключения пакета `signal` были заданы три входные последовательности: для построения обычных графиков кодирования, для проверки свойства самосинхронизации и для построения спектров. Затем для каждого кода были последовательно построены графики сигнала, что позволило визуально сравнить форму импульсов при разных способах кодирования.

13. Далее были построены графики для последовательности, предназначенной для анализа самосинхронизации. По полученным результатам можно было увидеть, что униполярное кодирование и NRZ не обеспечивают надёжной самосинхронизации, тогда как RZ, манчестерское и дифференциальное манчестерское кодирование содержат регулярные переходы сигнала и поэтому позволяют восстановить тактовую частоту.

14. На последнем шаге были построены спектры для всех исследуемых кодов. Анализ графиков показал, что различные способы кодирования формируют разные спектральные распределения, а значит по-разному влияют на требования к полосе пропускания линии связи и устойчивость передачи. 

# Выводы

В результате выполнения лабораторной работы были изучены основные методы кодирования и модуляции сигналов, а также получены практические навыки работы с Octave при построении графиков и спектров. В ходе выполнения заданий было показано, как ряд Фурье позволяет приближать импульсный сигнал, как быстрое преобразование Фурье используется для спектрального анализа и как амплитудная модуляция изменяет частотный состав сигнала.

Кроме того, были исследованы различные способы кодирования битовых последовательностей и сделан вывод о том, что наличие регулярных переходов уровня сигнала существенно влияет на возможность самосинхронизации. Наиболее информативными с точки зрения синхронизации оказались RZ, манчестерское и дифференциальное манчестерское кодирование, тогда как униполярный код и NRZ обладают этим свойством в значительно меньшей степени. 

# Список литературы{.unnumbered}

::: {#refs}
:::
